collections:
  - name: community.docker
  - name: community.general
  - name: community.grafana
  - name: community.kubernetes
  - name: community.mongodb
  - name: community.mysql
  - name: community.postgresql
  - name: community.proxysql
  - name: ansible.posix
  - name: kubernetes.core
    version: 2.1.1
