---

inventories:

  - name: vlan101
    groups: !include _vlan101.yaml

  - name: vlan10
    groups: !include _vlan10.yaml

  - name: vlan20
    groups: !include _vlan20.yaml

  - name: vlan30
    groups: !include _vlan30.yaml

  - name: vlan40
    groups: !include _vlan40.yaml

  - name: vlan50
    groups: !include _vlan50.yaml

  - name: vlan60
    groups: !include _vlan60.yaml

  - name: vlan70
    groups: !include _vlan70.yaml

  - name: vlan80
    groups: !include _vlan80.yaml
