- hosts: "{{ target | default('test') }}"
  order: inventory
  become: yes
  gather_facts: yes
  any_errors_fatal: true

  pre_tasks:
    - name: Install Python for Ansible.
      raw: bash -c "test -e /usr/bin/python3 || (apt -qqy update && apt install -qy python3-minimal)"
      register: pythonable
      changed_when: pythonable.stdout

  roles:
    - willshersystems.sshd
    - oefenweb.timezone
    - oefenweb.fail2ban
