---

# Usage:
# ansible-playbook -i inventories/hosts playbooks/password.yml -e "target=your_inventory_group username=ubuntu password='TopSecret'"

- hosts: "{{ target | default('test') }}"
  order: inventory
  become: yes
  gather_facts: yes

  tasks:
    - name: Change User Password
      user:
        name: "{{ username }}"
        update_password: always
        password: "{{ password | password_hash('sha512') }}"

    - debug: msg="The Secret is {{ password }}"
