---

# Usage:
# ansible-playbook -i inventories/hosts playbooks/password.yml -e "target=your_inventory_group username=ubuntu password='SECRET' authorized_key='ssh-rsa your-public-key'"

- hosts: "{{ target | default('test') }}"
  order: inventory
  become: yes
  gather_facts: no

  vars:
    username: "ubuntu"
    password: "secret"
    authorized_key: "ssh-rsa your-public-key"

  tasks:
    - name: Update User Authorized_keys
      ansible.posix.authorized_key:
        user: "{{ username }}"
        key: "{{ authorized_key }}"
        state: present
        exclusive: True

    - name: Change User Password
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        update_password: always
        password: "{{ password | password_hash('sha512') }}"
